---
# http://about.travis-ci.org/docs/user/getting-started/

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

before_script:
  - 'bundle install'

script:
  - 'rake spec'

# http://about.travis-ci.org/docs/user/notifications/#Email-notifications
notifications:
  email: false
